sudo: false
language: 
  - rust
  - cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - cmake
env:
  matrix:
    - CC=/usr/bin/gcc-6 CXX=/usr/bin/g++-6
    - CC=clang CXX=clang++
rust:
  - stable
  - nightly
notifications:
  email:
    - s.pepyakin@gmail.com
before_script:
  - rustc --version
  - cargo --version
script:
  - cargo test --all --verbose
